package com.example;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 基于 HikariCP 的任务表访问。
 * 连接池的核心心智：连接是昂贵的（TCP + 认证 + 会话初始化，毫秒级），
 * 池子预先建好 N 条常驻连接，业务「借了还、还了再借」，把建连成本摊到启动期。
 */
public class TaskDao implements AutoCloseable {

    private final HikariDataSource dataSource;

    /** 建池即建连：maximumPoolSize 决定同时最多几条物理连接 */
    public TaskDao(String jdbcUrl, int maxPoolSize) {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(jdbcUrl);
        config.setUsername("sa");
        config.setPassword("");
        config.setMaximumPoolSize(maxPoolSize);
        this.dataSource = new HikariDataSource(config);
    }

    public void createTable() throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE tasks ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "title VARCHAR(128) NOT NULL)");
        }
    }

    /** 每次操作从池里借一条连接，try-with-resources 关闭即归还（不是真断开） */
    public long insert(String title) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO tasks(title) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, title);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return keys.getLong(1);
            }
        }
    }

    public int count() throws SQLException {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT COUNT(*) FROM tasks");
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return rs.getInt(1);
        }
    }

    /** 清表（测试隔离用） */
    public void clear() throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement st = conn.createStatement()) {
            st.execute("DELETE FROM tasks");
        }
    }

    /** 池的实时状态（供教学观察）：当前物理连接总数 / 活跃 / 空闲 */
    public String poolStats() {
        var mx = dataSource.getHikariPoolMXBean();
        return "total=" + mx.getTotalConnections()
                + ", active=" + mx.getActiveConnections()
                + ", idle=" + mx.getIdleConnections();
    }

    @Override
    public void close() {
        dataSource.close();   // 关池才真正断开全部物理连接
    }
}
