package com.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 账户表与转账事务。核心规则：
 * 转账 = 扣款 + 收款，两步必须「同生同死」——这就是事务的原子性（Atomicity）。
 * 事务边界由业务定义（一次转账），不由数据库决定。
 */
public class AccountDao {

    private final Connection conn;

    public AccountDao(Connection conn) {
        this.conn = conn;
    }

    public void createTable() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE accounts ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "owner VARCHAR(64) NOT NULL, "
                    + "balance_cents BIGINT NOT NULL CHECK (balance_cents >= 0))");
        }
    }

    public long open(String owner, long balanceCents) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO accounts(owner, balance_cents) VALUES (?, ?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, owner);
            ps.setLong(2, balanceCents);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return keys.getLong(1);
            }
        }
    }

    public long balanceCents(long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT balance_cents FROM accounts WHERE id = ?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    throw new SQLException("账户不存在: " + id);
                }
                return rs.getLong(1);
            }
        }
    }

    /**
     * 转账（金额单位：分）。任何一步失败都整体回滚，数据库回到转账前状态。
     *
     * @throws IllegalStateException 余额不足或收款账户不存在（业务失败，已回滚）
     * @throws SQLException          数据库故障（已回滚）
     */
    public void transferCents(long fromId, long toId, long amountCents) throws SQLException {
        if (amountCents <= 0) {
            throw new IllegalArgumentException("转账金额必须为正数");
        }
        boolean prevAutoCommit = conn.getAutoCommit();
        conn.setAutoCommit(false);   // —— 事务从这里开始
        try {
            // 1. 扣款：WHERE 里带余额条件，余额不足时影响 0 行（数据库帮我们守住底线）
            try (PreparedStatement debit = conn.prepareStatement(
                    "UPDATE accounts SET balance_cents = balance_cents - ? WHERE id = ? AND balance_cents >= ?")) {
                debit.setLong(1, amountCents);
                debit.setLong(2, fromId);
                debit.setLong(3, amountCents);
                if (debit.executeUpdate() == 0) {
                    throw new IllegalStateException("余额不足或付款账户不存在: " + fromId);
                }
            }
            // 2. 收款：账户不存在时影响 0 行——此刻扣款已发生，必须回滚
            try (PreparedStatement credit = conn.prepareStatement(
                    "UPDATE accounts SET balance_cents = balance_cents + ? WHERE id = ?")) {
                credit.setLong(1, amountCents);
                credit.setLong(2, toId);
                if (credit.executeUpdate() == 0) {
                    throw new IllegalStateException("收款账户不存在: " + toId);
                }
            }
            conn.commit();   // —— 两步都成功，事务落盘
        } catch (SQLException | RuntimeException e) {
            conn.rollback();   // —— 任何一步失败，撤销本事务的全部写入
            throw e;
        } finally {
            conn.setAutoCommit(prevAutoCommit);   // 恢复现场，连接可复用
        }
    }
}
