// exercises/sol-04-payment-aop-tx.java —— 练习 4 参考实现：支付服务的 AOP 耗时切面 + 事务回滚规则
// 验证环境：OpenJDK 17.0.18 + Maven 3.9.12 + Spring Framework 6.1.6 + HSQLDB 2.5.0（纯核心容器）
// 验证状态：已验证（本机离线 mvn -o test，BUILD SUCCESS）
// 实测结果：Tests run: 3, Failures: 0, Errors: 0
//   （payDeductsAndAuditsInSeparateTransaction：扣款成功 + REQUIRES_NEW 审计独立落库；
//     insufficientBalanceRollsBackWithoutSideEffects：余额不足抛业务异常 → 无任何副作用（余额不变、审计 0 条）；
//     aspectCountsProxiedPayCalls：每次经代理的 pay 调用切面计数 +1）
// ---------------------------------------------------------------------------
// 本练习工程 = 标准 Maven 工程（pom 复制 ../examples/ex04-spring-aop-transaction/pom.xml，
//   artifactId 改 sol04-pay-aop-tx）+ 下列文件。验证命令：mvn -o -Dmaven.repo.local=/tmp/m2clone test
// 教学点：业务异常 = 运行时异常 → @Transactional 默认回滚；受检异常默认不回滚（要 rollbackFor，
//   见 ex04 实测）；「扣款成功但审计失败」用 REQUIRES_NEW 把审计放进独立事务——传播行为是
//   事务边界设计的核心工具；切面与事务共用代理（自调用陷阱见 ex04）。
// ===========================================================================
// src/main/resources/schema.sql
// ===========================================================================
-- sol-04：wallets 钱包余额；pay_audit 支付流水（REQUIRES_NEW 独立提交）
CREATE TABLE wallets (
    name    VARCHAR(50) PRIMARY KEY,
    balance INT NOT NULL
);

CREATE TABLE pay_audit (
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no  VARCHAR(50),
    amount    INT
);

// ===========================================================================
// src/main/java/com/example/pay/PayTxConfig.java
// ===========================================================================
package com.example.pay;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.init.DataSourceInitializer;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;

import javax.sql.DataSource;

/** 装配中枢：与 examples/ex04 同构（Hikari + HSQLDB mem + JdbcTemplate + 事务 + AOP） */
@Configuration
@EnableAspectJAutoProxy
@EnableTransactionManagement
@ComponentScan(basePackages = "com.example.pay")
public class PayTxConfig {

    @Bean
    public DataSource dataSource() {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:hsqldb:mem:paydb");
        config.setUsername("sa");
        config.setPassword("");
        config.setMaximumPoolSize(4);
        return new HikariDataSource(config);
    }

    @Bean
    public JdbcTemplate jdbcTemplate(DataSource dataSource) {
        return new JdbcTemplate(dataSource);
    }

    @Bean
    public PlatformTransactionManager transactionManager(DataSource dataSource) {
        return new DataSourceTransactionManager(dataSource);
    }

    @Bean
    public DataSourceInitializer dataSourceInitializer(DataSource dataSource) {
        DataSourceInitializer initializer = new DataSourceInitializer();
        initializer.setDataSource(dataSource);
        initializer.setDatabasePopulator(new ResourceDatabasePopulator(new ClassPathResource("schema.sql")));
        return initializer;
    }
}

// ===========================================================================
// src/main/java/com/example/pay/PaymentService.java
// ===========================================================================
package com.example.pay;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * 支付服务：业务失败抛「业务异常」回滚扣款；审计流水 REQUIRES_NEW 独立落库；
 * 被拒支付（余额不足）抛出后外层不产生任何副作用——练习要求把「回滚规则」讲清楚。
 */
@Service
public class PaymentService {

    private final JdbcTemplate jdbc;
    private final ObjectProvider<PaymentService> self;

    public PaymentService(JdbcTemplate jdbc, ObjectProvider<PaymentService> self) {
        this.jdbc = jdbc;
        this.self = self;
    }

    public PaymentService proxiedSelf() {
        return self.getObject();
    }

    @Transactional
    public void openWallet(String name, int balance) {
        jdbc.update("INSERT INTO wallets(name, balance) VALUES (?, ?)", name, balance);
    }

    /** 支付：扣款 + 审计流水（REQUIRES_NEW）+ 余额不足抛业务异常（运行时 → 默认回滚） */
    @Transactional
    public void pay(String wallet, String orderNo, int amount) {
        int balance = balanceOf(wallet);
        if (balance < amount) {
            throw new InsufficientBalanceException("余额不足：需要 " + amount + "，当前 " + balance);
        }
        jdbc.update("UPDATE wallets SET balance = balance - ? WHERE name = ?", amount, wallet);
        proxiedSelf().audit(orderNo, amount); // REQUIRES_NEW：审计独立提交，主事务失败它也在
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void audit(String orderNo, int amount) {
        jdbc.update("INSERT INTO pay_audit(order_no, amount) VALUES (?, ?)", orderNo, amount);
    }

    @Transactional(readOnly = true)
    public int balanceOf(String name) {
        Integer b = jdbc.queryForObject("SELECT balance FROM wallets WHERE name = ?", Integer.class, name);
        return b == null ? -1 : b;
    }

    public int auditCount(String orderPrefix) {
        Integer n = jdbc.queryForObject(
                "SELECT COUNT(*) FROM pay_audit WHERE order_no LIKE ?", Integer.class, orderPrefix + "%");
        return n == null ? 0 : n;
    }

    /** 业务异常（运行时）：触发 @Transactional 默认回滚规则 */
    public static final class InsufficientBalanceException extends IllegalStateException {
        public InsufficientBalanceException(String message) {
            super(message);
        }
    }
}

// ===========================================================================
// src/main/java/com/example/pay/PaymentAuditAspect.java
// ===========================================================================
package com.example.pay;

import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.concurrent.atomic.AtomicInteger;

/** 支付耗时切面：@Around 记录每个经过代理的支付调用（配合事务代理同源机制） */
@Aspect
@Component
public class PaymentAuditAspect {

    private static final Logger log = LoggerFactory.getLogger(PaymentAuditAspect.class);
    private final AtomicInteger proxiedCalls = new AtomicInteger();

    @Around("execution(* com.example.pay.PaymentService.pay(..))")
    public Object timePay(ProceedingJoinPoint pjp) throws Throwable {
        proxiedCalls.incrementAndGet();
        long start = System.nanoTime();
        try {
            Object result = pjp.proceed();
            log.info("pay 成功，耗时 {} ms", (System.nanoTime() - start) / 1_000_000);
            return result;
        } catch (Throwable t) {
            log.warn("pay 失败：{}", t.getMessage());
            throw t;
        }
    }

    public int payCallCount() {
        return proxiedCalls.get();
    }
}

// ===========================================================================
// src/test/java/com/example/pay/PaymentTxTest.java
// ===========================================================================
package com.example.pay;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * sol-04 测试：支付成功扣款 + 审计落库；余额不足 → 业务异常回滚（无任何副作用）；
 * 切面计数验证代理生效。
 * 验证命令：mvn -o -Dmaven.repo.local=/tmp/m2clone test
 */
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = PayTxConfig.class)
class PaymentTxTest {

    @Autowired
    private PaymentService paymentService;

    @Autowired
    private PaymentAuditAspect aspect;

    @Test
    void payDeductsAndAuditsInSeparateTransaction() {
        paymentService.openWallet("wallet-a", 100);
        paymentService.pay("wallet-a", "ORD-001", 30);
        assertThat(paymentService.balanceOf("wallet-a")).isEqualTo(70);
        assertThat(paymentService.auditCount("ORD-001")).isEqualTo(1);
    }

    /** 余额不足：业务异常（运行时）→ 主事务回滚，且 REQUIRES_NEW 审计也不该产生 */
    @Test
    void insufficientBalanceRollsBackWithoutSideEffects() {
        paymentService.openWallet("wallet-b", 10);
        assertThatThrownBy(() -> paymentService.pay("wallet-b", "ORD-002", 50))
                .isInstanceOf(PaymentService.InsufficientBalanceException.class);
        assertThat(paymentService.balanceOf("wallet-b")).isEqualTo(10);   // 扣款没发生
        assertThat(paymentService.auditCount("ORD-002")).isEqualTo(0);    // 审计在异常前根本没执行
    }

    /** 切面计数：每次经代理的 pay 调用 +1 */
    @Test
    void aspectCountsProxiedPayCalls() {
        paymentService.openWallet("wallet-c", 100);
        long before = aspect.payCallCount();
        paymentService.pay("wallet-c", "ORD-003", 5);
        assertThat(aspect.payCallCount()).isEqualTo(before + 1);
    }
}

