package com.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 索引与查询计划实验台：造数、看执行计划（EXPLAIN PLAN FOR）、计时对比。
 * 核心心智：没有索引的等值查询 = 全表扫描（成本随行数线性涨）；
 * 有索引 = 走 B+ 树定位（成本约 log N），代价是写入时要同步维护索引。
 */
public class IndexLab {

    private final Connection conn;

    public IndexLab(Connection conn) {
        this.conn = conn;
    }

    public void createTable() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(64), "
                    + "email VARCHAR(128))");
        }
    }

    /** 批量造数：addBatch + executeBatch，关自动提交一次落盘 */
    public void seed(int rows) throws SQLException {
        boolean prev = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO users(name, email) VALUES (?, ?)")) {
            for (int i = 0; i < rows; i++) {
                ps.setString(1, "user" + i);
                ps.setString(2, "u" + i + "@x.com");
                ps.addBatch();
            }
            ps.executeBatch();
            conn.commit();
        } finally {
            conn.setAutoCommit(prev);
        }
    }

    /** HSQLDB 的 EXPLAIN PLAN FOR：返回执行计划文本（其他库是 EXPLAIN / EXPLAIN ANALYZE） */
    public String planFor(String sql) throws SQLException {
        StringBuilder plan = new StringBuilder();
        try (PreparedStatement ps = conn.prepareStatement("EXPLAIN PLAN FOR " + sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                plan.append(rs.getString(1)).append('\n');
            }
        }
        return plan.toString();
    }

    /** 按 email 等值查询 n 次，返回总耗时（毫秒）——慢查询的 Java 侧度量 */
    public long timeEmailLookup(String email, int times) throws SQLException {
        long start = System.nanoTime();
        try (PreparedStatement ps = conn.prepareStatement("SELECT * FROM users WHERE email = ?")) {
            for (int i = 0; i < times; i++) {
                ps.setString(1, email);
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        rs.getString("name");
                    }
                }
            }
        }
        return (System.nanoTime() - start) / 1_000_000;
    }

    public void createEmailIndex() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE INDEX idx_users_email ON users(email)");
        }
    }

    public void dropEmailIndex() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("DROP INDEX idx_users_email");
        }
    }
}
