package com.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * 基于 JDBC 的用户表 CRUD。全部写路径走 PreparedStatement：
 * 参数经驱动转义传输，永远不会被拼进 SQL 文本——这是防 SQL 注入的根基。
 */
public class UserDao {

    /** 一行 users 记录：record 不可变，天然适合做「从 ResultSet 映射出来的数据」 */
    public record User(long id, String name, String email) {}

    private final Connection conn;

    public UserDao(Connection conn) {
        this.conn = conn;
    }

    /** DDL 用普通 Statement 即可：没有用户输入参数，不存在注入面 */
    public void createTable() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(64) NOT NULL, "
                    + "email VARCHAR(128) NOT NULL UNIQUE)");
        }
    }

    /** 插入并取回数据库生成的自增主键（RETURN_GENERATED_KEYS） */
    public long insert(String name, String email) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO users(name, email) VALUES (?, ?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, name);   // 占位符从 1 开始编号
            ps.setString(2, email);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return keys.getLong(1);
            }
        }
    }

    /** 按主键查询：ResultSet 游标初始在第一行之前，先 next() 再取值 */
    public Optional<User> findById(long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, name, email FROM users WHERE id = ?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(new User(
                            rs.getLong("id"), rs.getString("name"), rs.getString("email")));
                }
                return Optional.empty();
            }
        }
    }

    public List<User> findAll() throws SQLException {
        List<User> users = new ArrayList<>();
        try (PreparedStatement ps = conn.prepareStatement(
                     "SELECT id, name, email FROM users ORDER BY id");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                users.add(new User(
                        rs.getLong("id"), rs.getString("name"), rs.getString("email")));
            }
        }
        return users;
    }

    /** 更新返回受影响行数：0 行表示目标不存在 */
    public int updateEmail(long id, String newEmail) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE users SET email = ? WHERE id = ?")) {
            ps.setString(1, newEmail);
            ps.setLong(2, id);
            return ps.executeUpdate();
        }
    }

    public int delete(long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("DELETE FROM users WHERE id = ?")) {
            ps.setLong(1, id);
            return ps.executeUpdate();
        }
    }

    public int count() throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("SELECT COUNT(*) FROM users");
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return rs.getInt(1);
        }
    }
}
