-- V1：建用户表（Flyway 按版本号顺序执行，已执行的版本记录在 flyway_schema_history 表）
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(128) NOT NULL UNIQUE
);
