package com.example.users;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * 集成测试：真实 JDBC 代码 + HSQLDB 内存库（纯 Java，无需 Docker），
 * 验证「代码 + SQL」与真实数据库引擎协作。Testcontainers（真容器）见 examples/ex07，本沙箱无 Docker 未实跑。
 * 注意：类名不用 *IT 后缀 —— surefire 默认只跑 *Test/*Tests/*TestCase，*IT 是 failsafe（ph11）的约定。
 */
class JdbcUserRepositoryTest {

    private static Connection conn;
    private JdbcUserRepository repo;

    @BeforeAll
    static void openDb() throws Exception {
        conn = DriverManager.getConnection("jdbc:hsqldb:mem:userdb", "sa", "");
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(64) NOT NULL, "
                    + "email VARCHAR(128) NOT NULL UNIQUE)");
        }
    }

    @AfterAll
    static void closeDb() throws Exception {
        conn.close();
    }

    @BeforeEach
    void setUp() throws Exception {
        try (Statement st = conn.createStatement()) {
            st.execute("DELETE FROM users");
        }
        repo = new JdbcUserRepository(conn);
    }

    @Test
    void save_assignsDatabaseGeneratedId() {
        User saved = repo.save(new User(0L, "mosslau", "m@x.com"));

        assertThat(saved.id()).isPositive();
        assertThat(saved.name()).isEqualTo("mosslau");
    }

    @Test
    void save_thenFindById_roundTrips() {
        User saved = repo.save(new User(0L, "mosslau", "m@x.com"));

        User found = repo.findById(saved.id()).orElseThrow();
        assertThat(found.name()).isEqualTo("mosslau");
        assertThat(found.email()).isEqualTo("m@x.com");
    }

    @Test
    void findById_missing_returnsEmpty() {
        assertThat(repo.findById(999L)).isEmpty();
    }

    @Test
    void existsByEmail_trueAfterSave_falseAfterDelete() {
        User saved = repo.save(new User(0L, "bob", "bob@x.com"));

        assertThat(repo.existsByEmail("bob@x.com")).isTrue();
        assertThat(repo.deleteById(saved.id())).isTrue();
        assertThat(repo.existsByEmail("bob@x.com")).isFalse();
    }

    @Test
    void deleteById_missing_returnsFalse() {
        assertThat(repo.deleteById(999L)).isFalse();
    }

    @Test
    void save_duplicateEmail_violatesUniqueConstraint() {
        repo.save(new User(0L, "a", "same@x.com"));

        assertThatThrownBy(() -> repo.save(new User(0L, "b", "same@x.com")))
                .isInstanceOf(RuntimeException.class)
                .hasCauseInstanceOf(java.sql.SQLException.class);
    }
}
