// exercises/sol-02-transaction-transfer.java —— 练习 2 参考实现：事务转账（HSQLDB 内存库）
// 验证环境：OpenJDK 17.0.18 + Maven 3.9.12 + JUnit Jupiter 5.10.1 + HSQLDB 2.5.0（本机离线模式 mvn -o）
// 验证状态：已验证（pom 与下述全部源码放入临时工程后 mvn -o clean test, BUILD SUCCESS）
// 实测结果：Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
// ---------------------------------------------------------------------------
// 本练习的 pom.xml（写入工程根目录 pom.xml）:
//
//   <project xmlns="http://maven.apache.org/POM/4.0.0">
//     <modelVersion>4.0.0</modelVersion>
//     <groupId>com.example</groupId>
//     <artifactId>sol02-transaction-transfer</artifactId>
//     <version>1.0-SNAPSHOT</version>
//     <properties>
//       <maven.compiler.release>17</maven.compiler.release>
//       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
//     </properties>
//     <dependencies>
//       <dependency>
//         <groupId>org.hsqldb</groupId>
//         <artifactId>hsqldb</artifactId>
//         <version>2.5.0</version>
//       </dependency>
//       <dependency>
//         <groupId>org.junit.jupiter</groupId>
//         <artifactId>junit-jupiter</artifactId>
//         <version>5.10.1</version>
//         <scope>test</scope>
//       </dependency>
//     </dependencies>
//     <build>
//       <plugins>
//         <plugin>
//           <groupId>org.apache.maven.plugins</groupId>
//           <artifactId>maven-surefire-plugin</artifactId>
//           <version>3.2.5</version>
//         </plugin>
//       </plugins>
//     </build>
//   </project>
//
// 本文件内容放 src/main/java/com/example/TransferAccount.java
//
// 测试类（src/test/java/com/example/TransferAccountTest.java）:
//
//   package com.example;
//   import static org.junit.jupiter.api.Assertions.*;
//   import java.sql.Connection;
//   import java.sql.DriverManager;
//   import org.junit.jupiter.api.*;
//
//   class TransferAccountTest {
//       private static Connection conn;
//       private static TransferAccount dao;
//
//       @BeforeAll static void openDb() throws Exception {
//           conn = DriverManager.getConnection("jdbc:hsqldb:mem:sol02db", "sa", "");
//           dao = new TransferAccount(conn);
//           dao.createTable();
//       }
//       @AfterAll static void closeDb() throws Exception { conn.close(); }
//       @BeforeEach void clear() throws Exception {
//           try (var st = conn.createStatement()) { st.execute("DELETE FROM accounts"); }
//       }
//
//       @Test void successfulTransfer_commitsBothUpdates() throws Exception {
//           long alice = dao.open("alice", 100_00);
//           long bob = dao.open("bob", 50_00);
//           dao.transferCents(alice, bob, 30_00);
//           assertEquals(70_00, dao.balanceCents(alice));
//           assertEquals(80_00, dao.balanceCents(bob));
//       }
//       @Test void insufficientFunds_leavesBothBalancesUntouched() throws Exception {
//           long alice = dao.open("alice", 10_00);
//           long bob = dao.open("bob", 50_00);
//           IllegalStateException ex = assertThrows(IllegalStateException.class,
//                   () -> dao.transferCents(alice, bob, 99_00));
//           assertEquals("余额不足或付款账户不存在: " + alice, ex.getMessage());
//           assertEquals(10_00, dao.balanceCents(alice));
//           assertEquals(50_00, dao.balanceCents(bob));
//       }
//       @Test void missingPayee_rollsBackTheDebit() throws Exception {
//           long alice = dao.open("alice", 100_00);
//           assertThrows(IllegalStateException.class,
//                   () -> dao.transferCents(alice, 999L, 30_00));
//           assertEquals(100_00, dao.balanceCents(alice),
//                   "扣款语句实际执行过，没有回滚机制的话这里只剩 70");
//       }
//   }
//
// 编译/运行命令（工程根目录）:
//   1. mvn clean test
//       # 实测: Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
// 要点：
//   - 事务边界由业务定义：setAutoCommit(false) 到 commit() 之间就是「一次转账」
//   - 余额不足用 SQL 条件 WHERE balance_cents >= ? 守底线（影响 0 行），而不是先 SELECT 再判断
//   - 收款账户不存在时扣款已执行——rollback() 把它撤销（rollback 语义的直接证据）
//   - finally 恢复 autoCommit：连接会被复用，不恢复就把事务状态泄漏给下一位借用者
//   - 金额用「分」（long），不用 double/float——金钱计算禁止浮点数
// ---------------------------------------------------------------------------

package com.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/** 练习 2 参考实现：账户表与转账事务 */
public class TransferAccount {

    private final Connection conn;

    public TransferAccount(Connection conn) {
        this.conn = conn;
    }

    public void createTable() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE accounts ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "owner VARCHAR(64) NOT NULL, "
                    + "balance_cents BIGINT NOT NULL CHECK (balance_cents >= 0))");
        }
    }

    public long open(String owner, long balanceCents) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO accounts(owner, balance_cents) VALUES (?, ?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, owner);
            ps.setLong(2, balanceCents);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return keys.getLong(1);
            }
        }
    }

    public long balanceCents(long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT balance_cents FROM accounts WHERE id = ?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    throw new SQLException("账户不存在: " + id);
                }
                return rs.getLong(1);
            }
        }
    }

    /**
     * 转账（金额单位：分）。任何一步失败都整体回滚，数据库回到转账前状态。
     *
     * @throws IllegalStateException 余额不足或收款账户不存在（业务失败，已回滚）
     * @throws SQLException          数据库故障（已回滚）
     */
    public void transferCents(long fromId, long toId, long amountCents) throws SQLException {
        if (amountCents <= 0) {
            throw new IllegalArgumentException("转账金额必须为正数");
        }
        boolean prevAutoCommit = conn.getAutoCommit();
        conn.setAutoCommit(false);   // —— 事务从这里开始
        try {
            // 1. 扣款：WHERE 里带余额条件，余额不足时影响 0 行（数据库帮我们守住底线）
            try (PreparedStatement debit = conn.prepareStatement(
                    "UPDATE accounts SET balance_cents = balance_cents - ? WHERE id = ? AND balance_cents >= ?")) {
                debit.setLong(1, amountCents);
                debit.setLong(2, fromId);
                debit.setLong(3, amountCents);
                if (debit.executeUpdate() == 0) {
                    throw new IllegalStateException("余额不足或付款账户不存在: " + fromId);
                }
            }
            // 2. 收款：账户不存在时影响 0 行——此刻扣款已发生，必须回滚
            try (PreparedStatement credit = conn.prepareStatement(
                    "UPDATE accounts SET balance_cents = balance_cents + ? WHERE id = ?")) {
                credit.setLong(1, amountCents);
                credit.setLong(2, toId);
                if (credit.executeUpdate() == 0) {
                    throw new IllegalStateException("收款账户不存在: " + toId);
                }
            }
            conn.commit();   // —— 两步都成功，事务落盘
        } catch (SQLException | RuntimeException e) {
            conn.rollback();   // —— 任何一步失败，撤销本事务的全部写入
            throw e;
        } finally {
            conn.setAutoCommit(prevAutoCommit);   // 恢复现场，连接可复用
        }
    }
}
