// exercises/sol-05-index-slowquery.java —— 练习 5 参考实现：索引与慢查询（HSQLDB 内存库）
// 验证环境：OpenJDK 17.0.18 + Maven 3.9.12 + JUnit Jupiter 5.10.1 + HSQLDB 2.5.0（本机离线模式 mvn -o）
// 验证状态：已验证（pom 与下述全部源码放入临时工程后 mvn -o clean test, BUILD SUCCESS）
// 实测结果：Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
// 实测计时：20000 行 × 100 次等值查询: 无索引 80 ms, 有索引 1 ms（本机数值，你的机器可能不同但方向一致）
// ---------------------------------------------------------------------------
// 本练习的 pom.xml（写入工程根目录 pom.xml）:
//
//   <project xmlns="http://maven.apache.org/POM/4.0.0">
//     <modelVersion>4.0.0</modelVersion>
//     <groupId>com.example</groupId>
//     <artifactId>sol05-index-slowquery</artifactId>
//     <version>1.0-SNAPSHOT</version>
//     <properties>
//       <maven.compiler.release>17</maven.compiler.release>
//       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
//     </properties>
//     <dependencies>
//       <dependency>
//         <groupId>org.hsqldb</groupId>
//         <artifactId>hsqldb</artifactId>
//         <version>2.5.0</version>
//       </dependency>
//       <dependency>
//         <groupId>org.junit.jupiter</groupId>
//         <artifactId>junit-jupiter</artifactId>
//         <version>5.10.1</version>
//         <scope>test</scope>
//       </dependency>
//     </dependencies>
//     <build>
//       <plugins>
//         <plugin>
//           <groupId>org.apache.maven.plugins</groupId>
//           <artifactId>maven-surefire-plugin</artifactId>
//           <version>3.2.5</version>
//         </plugin>
//       </plugins>
//     </build>
//   </project>
//
// 本文件内容放 src/main/java/com/example/IndexLab.java
//
// 测试类（src/test/java/com/example/IndexLabTest.java）:
//   —— 注意按 @Order 共享同一张表（造数贵只做一次），这是「集成测试共享昂贵环境」的合理例外
//
//   package com.example;
//   import static org.junit.jupiter.api.Assertions.*;
//   import java.sql.Connection;
//   import java.sql.DriverManager;
//   import org.junit.jupiter.api.*;
//
//   @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
//   class IndexLabTest {
//       private static final int ROWS = 20_000;
//       private static final int LOOKUPS = 100;
//       private static Connection conn;
//       private static IndexLab lab;
//
//       @BeforeAll static void openDb() throws Exception {
//           conn = DriverManager.getConnection("jdbc:hsqldb:mem:sol05db", "sa", "");
//           lab = new IndexLab(conn);
//           lab.createTable();
//           lab.seed(ROWS);
//       }
//       @AfterAll static void closeDb() throws Exception { conn.close(); }
//
//       @Test @Order(1)
//       void withoutIndex_planIsFullScan() throws Exception {
//           String plan = lab.planFor("SELECT * FROM users WHERE email = 'u19999@x.com'");
//           assertTrue(plan.contains("access=FULL SCAN"), "无索引时应全表扫描，实测计划:\n" + plan);
//       }
//       @Test @Order(2)
//       void withIndex_planUsesIndex() throws Exception {
//           lab.createEmailIndex();
//           String plan = lab.planFor("SELECT * FROM users WHERE email = 'u19999@x.com'");
//           assertFalse(plan.contains("access=FULL SCAN"), "有索引后不应再全表扫描");
//           assertTrue(plan.contains("IDX_USERS_EMAIL"), "计划里应出现索引名，实测计划:\n" + plan);
//       }
//       @Test @Order(3)
//       void indexedLookup_isMeasurablyFaster() throws Exception {
//           long indexedMs = lab.timeEmailLookup("u19999@x.com", LOOKUPS);
//           lab.dropEmailIndex();
//           long noIndexMs = lab.timeEmailLookup("u19999@x.com", LOOKUPS);
//           lab.createEmailIndex();   // 恢复现场
//           System.out.printf("[IndexLab] %d 行 × %d 次等值查询: 无索引 %d ms, 有索引 %d ms%n",
//                   ROWS, LOOKUPS, noIndexMs, indexedMs);
//           assertTrue(indexedMs < noIndexMs,
//                   "走索引应更快: 无索引 " + noIndexMs + " ms, 有索引 " + indexedMs + " ms");
//       }
//   }
//
// 编译/运行命令（工程根目录）:
//   1. mvn clean test
//       # 实测: Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
// 要点：
//   - 无索引等值查询 = 全表扫描（O(N)）；有索引 = B+ 树定位（O(log N)），20000 行 × 100 次实测 78ms → 1ms
//   - EXPLAIN PLAN FOR 看执行计划：access=FULL SCAN vs 出现索引名——用计划验证而非假设
//   - addBatch + executeBatch 批量造数：关自动提交一次落盘，比逐条 executeUpdate 快一个数量级
//   - 索引影响查询和写入成本：写入要同步维护索引树，读多写少的列才值得建索引
// ---------------------------------------------------------------------------

package com.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/** 练习 5 参考实现：索引与查询计划实验台 */
public class IndexLab {

    private final Connection conn;

    public IndexLab(Connection conn) {
        this.conn = conn;
    }

    public void createTable() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE TABLE users ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(64), "
                    + "email VARCHAR(128))");
        }
    }

    /** 批量造数：addBatch + executeBatch，关自动提交一次落盘 */
    public void seed(int rows) throws SQLException {
        boolean prev = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO users(name, email) VALUES (?, ?)")) {
            for (int i = 0; i < rows; i++) {
                ps.setString(1, "user" + i);
                ps.setString(2, "u" + i + "@x.com");
                ps.addBatch();
            }
            ps.executeBatch();
            conn.commit();
        } finally {
            conn.setAutoCommit(prev);
        }
    }

    /** HSQLDB 的 EXPLAIN PLAN FOR：返回执行计划文本（其他库是 EXPLAIN / EXPLAIN ANALYZE） */
    public String planFor(String sql) throws SQLException {
        StringBuilder plan = new StringBuilder();
        try (PreparedStatement ps = conn.prepareStatement("EXPLAIN PLAN FOR " + sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                plan.append(rs.getString(1)).append('\n');
            }
        }
        return plan.toString();
    }

    /** 按 email 等值查询 n 次，返回总耗时（毫秒）——慢查询的 Java 侧度量 */
    public long timeEmailLookup(String email, int times) throws SQLException {
        long start = System.nanoTime();
        try (PreparedStatement ps = conn.prepareStatement("SELECT * FROM users WHERE email = ?")) {
            for (int i = 0; i < times; i++) {
                ps.setString(1, email);
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        rs.getString("name");
                    }
                }
            }
        }
        return (System.nanoTime() - start) / 1_000_000;
    }

    public void createEmailIndex() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("CREATE INDEX idx_users_email ON users(email)");
        }
    }

    public void dropEmailIndex() throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.execute("DROP INDEX idx_users_email");
        }
    }
}
