-- ex04 schema：accounts 转账账户、events 事件流水（REQUIRES_NEW 演示用）
CREATE TABLE accounts (
    name    VARCHAR(50) PRIMARY KEY,
    balance INT NOT NULL
);

CREATE TABLE events (
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(100)
);
